/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CRM;

/**
 *
 * @author sasha
 */
public class customerDetails extends javax.swing.JFrame {

    /**
     * Creates new form customerDetails
     */
    public customerDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inName = new javax.swing.JTextField();
        inEmail = new javax.swing.JTextField();
        inPhone = new javax.swing.JTextField();
        inResponsible = new javax.swing.JTextField();
        inStatus = new javax.swing.JTextField();
        btnClose = new javax.swing.JButton();
        btnMedium = new javax.swing.JButton();
        btnMinimize = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnCusOffers = new javax.swing.JButton();
        btnCusInvoices = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nazwa");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 80, -1, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 130, -1, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Numer telefonu");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 180, -1, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Osoba odpowiedzialna");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 230, -1, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Status");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 280, -1, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("1 z 1");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 15, 70, 20));
        getContentPane().add(inName, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 105, 200, 20));
        getContentPane().add(inEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 155, 200, 20));
        getContentPane().add(inPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 205, 200, 20));
        getContentPane().add(inResponsible, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 255, 200, 20));
        getContentPane().add(inStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 305, 200, 20));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/crossIcon.png"))); // NOI18N
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(935, 5, 20, 20));

        btnMedium.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mediumIcon.png"))); // NOI18N
        btnMedium.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnMedium, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 5, 20, 20));

        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimizeIcon.png"))); // NOI18N
        btnMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(885, 5, 20, 20));

        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/saveIcon.png"))); // NOI18N
        btnSave.setText("Zapisz");
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 120, 20));

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trashIcon.png"))); // NOI18N
        btnDelete.setText("Usuń");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 30, 120, 20));

        btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lArrowIcon.png"))); // NOI18N
        btnPrev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 15, 20, 20));

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rArrowIcon.png"))); // NOI18N
        btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 15, 20, 20));

        btnCusOffers.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCusOffers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/offerIcon.png"))); // NOI18N
        btnCusOffers.setText("Oferty");
        btnCusOffers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCusOffers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCusOffersActionPerformed(evt);
            }
        });
        getContentPane().add(btnCusOffers, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 55, 120, 20));

        btnCusInvoices.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCusInvoices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/invoiceIcon.png"))); // NOI18N
        btnCusInvoices.setText("Faktury");
        btnCusInvoices.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnCusInvoices, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 55, 120, 20));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(700, 445));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Numer", "Status", "Wartość netto", "VAT (%)", "Wartość brutto", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Double.class, java.lang.Byte.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setMaximumSize(new java.awt.Dimension(2147483647, 1130));
        jTable2.setMinimumSize(new java.awt.Dimension(60, 1130));
        jTable2.setPreferredSize(new java.awt.Dimension(700, 455));
        jTable2.setShowGrid(true);
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 80, 700, 455));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Background.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCusOffersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCusOffersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCusOffersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnCusInvoices;
    private javax.swing.JButton btnCusOffers;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnMedium;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField inEmail;
    private javax.swing.JTextField inName;
    private javax.swing.JTextField inPhone;
    private javax.swing.JTextField inResponsible;
    private javax.swing.JTextField inStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
